### ISSUE TITLE
Does Windows system support?

### ISSUE THREAD

**Issue by githubfzq** [guzman-raphael/matlab#1] opened 2019-09-29 05:32 UTC
I have docker for Windows10, and I have the license of Matlab on Windows. How can I set the license parameter and MAC parameter?

**Comment by guzman-raphael** [comment] 2019-11-20 15:02
@githubfzq Have not tried this yet but based on Mathworks portal, it seems to be that licenses are OS specific. In your account in Mathworks, navigate to `Licenses>Select Lincense>Install and Activate>View Current Activations`. That said, you can attempt it and see if it works. Depending on the error you get, we may be able to resolve it.

To utilize the license you have, you will need to pull the following details related to the license:
* HOSTID (Must be a MAC address)
* License File (To convert to env var see `README.md`. This will need to be done on a Linux machine.)
* Computer Login Name or system user associated with license. 

See `README.md` on how to set them properly.

**Comment by guzman-raphael** [comment] 2019-11-20 19:44
@githubfzq I have made some minor updates and confirmed your use case works; that being utilizing Windows-based MATLAB licenses with this image. 

Make sure to re-pull i.e. `docker pull raphaelguzman/matlab:R2018b-GUI` to grab the new updated version. 

On a side note, you may comment out the volume mount `- /tmp/.X11-unix:/tmp/.X11-unix:rw` if you are using the `docker-compose.yml` in this repo since you will be running this on a WIN docker host and thus this config is N/A.

**Comment by guzman-raphael** [comment] 2020-02-03 20:43
Closing since I believe the issue has been resolved. Feel free to open if this is incorrect with added details.

**Closed as completed by guzman-raphael** 2020-02-03 20:43 UTC
